from playwright.sync_api import sync_playwright

def verify_site_export():
    with sync_playwright() as p:
        browser = p.chromium.launch()
        page = browser.new_page()

        # Navigate to the static file generated by build
        # Since we ran 'npm run build', the output is in 'out' folder
        # We can use file:// protocol to check the static files directly
        import os
        cwd = os.getcwd()
        page.goto(f"file://{cwd}/out/index.html")

        # Take screenshot of homepage
        page.screenshot(path="verification/home.png")

        # Check about page link
        hakkimda_link = page.get_by_role("link", name="Hakkımda").first
        if hakkimda_link:
            # We can't easily click and navigate with file:// protocol for all relative links
            # without a proper server, but we can verify the href
            href = hakkimda_link.get_attribute("href")
            print(f"Hakkimda link href: {href}")

            # Manually navigate to check if page exists
            page.goto(f"file://{cwd}/out/hakkimda.html")
            page.screenshot(path="verification/about.png")

        browser.close()

if __name__ == "__main__":
    verify_site_export()
